### ISSUE TITLE
Misleading comment

### ISSUE THREAD

**Issue by VinayVasista** [tsbertalan/openmg#11]
In /openmg/__init__.py, comment on Optional params:

"If both threshold and cycles are > 0, the first
                    condition to be met will halt the v-cycling. If both are > 0,
                    ValueError is raised."

Please fix this.

**Comment by tsbertalan** [comment]
If you would like to fork the repository, make and commit the change, and
submit a pull request, I would be happy to provide you credit for it.

**Comment by VinayVasista** [comment]
Hey, thanks! But that's ok. I started looking at your
project when I was skimming through some multigrid
implementations. I don't know much about this code
base, so it would be really helpful for me if you would
correct the cases in the comment.

Cheers,
~ Vinay

**Comment by tsbertalan** [comment]
I went ahead and fixed it in 129e11fd1a to match what the code itself does. Thanks.
